### PR TITLE
feat: Restore Android 6 support

### PR DESCRIPTION
**Pull request by spieden**
Anecdotally running just fine on a couple of Sony XPeria Z3Cs with these changes

### CODE REVIEW

**Comment by spieden** [comment]
Well, I bought a couple budget old devices for my kids to have dedicated audiobook players and the stupid bootloaders are locked so I can't install LineageOS as planned. As such it's necessary for me but maybe I'm the only one left. :)

**Comment by advplyr** [comment]
I think you are the only one left so I'm going to close this out. It's not something I want to test before each release and if it is supported users would rightfully expect it to be fully functional which I can't be sure about.

**Comment by Homer-Sim** [comment]
No, he isn't the only one left :)
Which was the latest version working with Android 6?

**Comment by spieden** [comment]
@Homer-Sim We are successfully running a build I made off of my branch. Been meaning to try to make another one with the more recent upstream changes. I can send you the APK if you like. Not sure if our phones are on the same architecture or not.

**Comment by Homer-Sim** [comment]
> @Homer-Sim We are successfully running a build I made off of my branch. Been meaning to try to make another one with the more recent upstream changes. I can send you the APK if you like. Not sure if our phones are on the same architecture or not.

I would love to try it. More as not working cannot happen

**Comment by spieden** [comment]
[Here you go](https://user.fm/files/v2-06419da6f803c62894e7a6c437d9bd99/Audiobookshelf_0.9.66-restore-android-six-support.apk.zip)🤞

**Comment by Homer-Sim** [comment]
> @Homer-Sim We are successfully running a build I made off of my branch. Been meaning to try to make another one with the more recent upstream changes. I can send you the APK if you like. Not sure if our phones are on the same architecture or not.

I would love to try it. More as not working cannot happen

**Comment by Homer-Sim** [comment]
> [Here you go](https://user.fm/files/v2-06419da6f803c62894e7a6c437d9bd99/Audiobookshelf_0.9.66-restore-android-six-support.apk.zip)🤞

It is working!!!!!!!!!!!!
You made my and my sons day!!!
Thanks

**Comment by spieden** [comment]
Yay! I'll let you know if I successfully make a newer build.

**Pull request closed without merging**
