### PR TITLE
Media button & connect fail

### PR DESCRIPTION
**Pull request by svdztn**
### handle media button:
SeekBackward is often used, so I remap the button of headset.  
- button NEXT to seekBackward
- button PREVIOUS to seekForward
- double click button PLAY/PAUSE to seekBackward

### do not delete ServerUrl:
In the case of poor network, app fails to connect the server, then the `ServerUrl` will be deleted.  
We have to set `ServerUrl` and login again.

### CODE REVIEW

**Comment by advplyr** [comment]
The new way covers are handled on the server was not implemented yet and it was crashing, so I had to fix it to get this to run.
I tested and it worked great, thanks for helping out.

**Comment by svdztn** [comment]
correction：
> button NEXT to seekForward  
> button PREVIOUS to seekBackward

Glad to help, great project!

**Comment by advplyr** [comment]
This update is live on the google play store

**Comment by svdztn** [comment]
> This update is live on the google play store

Great, thanks for notice.

There is another user friendly function about auto seekBackward. The player should jump backward automatically after pause, the lenth of the jump depends on the total pause time. Longer the pause time, longer the seekBackward. (There's a max and min limit.)  
Clients of all platform should have this feature, I think.

**Pull request merged**
