### PR TITLE
Display current chapter in the iOS Now Playing widget instead of the overall book progress

### PR DESCRIPTION
**Pull request by ronaldheft**
* Implements #239 for iOS
* Right now, if a book has chapters it will display the chapter information, but I plan to tie this to "Chapter Track" setting on the player

### CODE REVIEW

**Comment by ajaxbits** [comment]
I have tested this on my iOS 16.3.1 device. Works great!

@ronaldheft is there any update on if you plan to merge this code? If there's anything I can do to help this feature get merged, I'd be happy to.

**Comment by johnpyp** [comment]
@ronaldheft Is there more work that needs to be done to get this out of draft or is it ready to go?

**Comment by ronaldheft** [comment]
It was close when I stopped work on it. The remaining feature is to tie to the "Chapter Track" setting on the player, so if someone prefers seeing the whole book's progress, this change does not interfere with that.

Additionally, since it's been over a year since this feature has been worked on, additional testing is required. There has been changes in the player since, and there is at least one merge conflict that needs to be resolved.

**Comment by benonymity** [comment]
Just added that last feature and fixed the conflicts over in #1002. Hope that's okay! If you'd prefer I can open a PR on your branch @ronaldheft instead so this existing PR can get merged instead.

**Comment by ronaldheft** [comment]
@benonymity That's fine by me! Thanks for picking up the work and getting it over the finish line!

**Pull request closed without merging**
